import React,{useEffect,useRef,useState}from'react';

const tr={en:{appName:'OmniTrack',tagline:'High School Daily Tracker & MDM',schedule:'Schedule',focus:'Focus Studio',tasks:'Tasks',matrix:'Priority Matrix',grades:'Grade Calculator',stats:'Analytics',whiteboard:'Whiteboard',album:'Gallery',blocker:'App Blocker',add:'Add',del:'Delete',time:'Time',title:'Title',location:'Location',task:'Task',date:'Due Date',priority:'Priority',high:'High',medium:'Medium',low:'Low',start:'Start Focus Session',pause:'Pause',stop:'End Session',minutes:'Minutes',sound:'Ambient Sound',pen:'Pen',eraser:'Eraser',clear:'Clear Canvas',arabic:'العربية',avg:'Average',total:'Total Study Time',sessions:'Completed Sessions',streak:'Active Streak'},ar:{appName:'أومني تراك',tagline:'متتبع الطالب اليومي',schedule:'الجدول',focus:'استوديو التركيز',tasks:'المهام',matrix:'مصفوفة الأولويات',grades:'حاسبة الدرجات',stats:'الإحصائيات',whiteboard:'السبورة',album:'الألبوم',blocker:'حظر التطبيقات',add:'إضافة',del:'حذف',time:'الوقت',title:'العنوان',location:'المكان',task:'المهمة',date:'تاريخ الاستحقاق',priority:'الأولوية',high:'عالية',medium:'متوسطة',low:'منخفضة',start:'بدء جلسة التركيز',pause:'إيقاف مؤقت',stop:'إنهاء الجلسة',minutes:'دقيقة',sound:'الصوت المحيط',pen:'قلم',eraser:'ممحاة',clear:'مسح اللوحة',arabic:'English',avg:'المتوسط',total:'إجمالي وقت الدراسة',sessions:'الجلسات المكتملة',streak:'سلسلة الأيام'}};
const today=()=>new Date().toISOString().slice(0,10);
function Card({children,className=''}){return <div className={'bg-slate-800 border border-slate-700 rounded-2xl p-6 shadow-lg '+className}>{children}</div>}
function App(){const[lang,setLang]=useState('en'),t=tr[lang],rtl=lang==='ar';const[tab,setTab]=useState('schedule');const[schedule,setSchedule]=useState([{id:1,time:'08:00 AM - 09:30 AM',title:'Advanced Mathematics',location:'Room 304'},{id:2,time:'09:45 AM - 11:15 AM',title:'Physics Laboratory',location:'Science Wing B'}]);const[tasks,setTasks]=useState([{id:1,title:'Calculus Problem Set #4',dueDate:today(),priority:'high',completed:false},{id:2,title:'Physics Lab Report',dueDate:today(),priority:'medium',completed:true}]);const[apps,setApps]=useState([{id:1,name:'Social Media Feed',locked:true},{id:2,name:'Video Streaming',locked:true},{id:3,name:'Mobile Gaming Portal',locked:true},{id:4,name:'Messaging App',locked:false}]);const[stats,setStats]=useState({minutes:125,sessions:5,streak:4});const[focus,setFocus]=useState(false);const[mins,setMins]=useState(25);const[remaining,setRemaining]=useState(1500);const[grades,setGrades]=useState([{id:1,name:'Mathematics',grade:94},{id:2,name:'Physics',grade:88},{id:3,name:'History',grade:91}]);const[photos,setPhotos]=useState([]);const tabs=[['schedule',t.schedule],['focus',t.focus],['tasks',t.tasks],['matrix',t.matrix],['grades',t.grades],['stats',t.stats],['whiteboard',t.whiteboard],['album',t.album],['blocker',t.blocker]];
useEffect(()=>{if(!focus)return;const x=setInterval(()=>setRemaining(v=>{if(v<=1){setFocus(false);setStats(s=>({...s,minutes:s.minutes+mins,sessions:s.sessions+1}));return mins*60}return v-1}),1000);return()=>clearInterval(x)},[focus,mins]);
useEffect(()=>{if(!focus)setRemaining(mins*60)},[mins,focus]);
const addSchedule=e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(!f.get('title'))return;setSchedule([...schedule,{id:Date.now(),time:f.get('time')||'09:00',title:f.get('title'),location:f.get('location')}]);e.currentTarget.reset()};
const addTask=e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(!f.get('task'))return;setTasks([...tasks,{id:Date.now(),title:f.get('task'),dueDate:f.get('date')||today(),priority:f.get('priority'),completed:false}]);e.currentTarget.reset()};
const addGrade=e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(!f.get('name'))return;setGrades([...grades,{id:Date.now(),name:f.get('name'),grade:Number(f.get('grade'))||0}]);e.currentTarget.reset()};
const time=`${String(Math.floor(remaining/60)).padStart(2,'0')}:${String(remaining%60).padStart(2,'0')}`;const avg=grades.length?(grades.reduce((a,x)=>a+x.grade,0)/grades.length).toFixed(1):'0';
return <div dir={rtl?'rtl':'ltr'} className="min-h-screen bg-slate-950 text-slate-100"><header className="sticky top-0 z-40 bg-slate-900/95 backdrop-blur border-b border-slate-800"><div className="max-w-6xl mx-auto px-4 py-3 flex justify-between items-center gap-3"><div className="flex items-center gap-3"><div className="w-10 h-10 rounded-xl bg-gradient-to-tr from-indigo-500 to-violet-600 grid place-items-center font-black">O</div><div><h1 className="text-xl font-black">{t.appName}</h1><p className="text-xs text-slate-400">{t.tagline}</p></div></div><button onClick={()=>setLang(lang==='en'?'ar':'en')} className="px-3 py-2 rounded-lg bg-slate-800 border border-slate-700 text-xs font-bold">{t.arabic}</button></div><nav className="max-w-6xl mx-auto px-4 pb-2 flex gap-1 overflow-x-auto scrollbar-none">{tabs.map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={'px-4 py-2 rounded-lg whitespace-nowrap text-sm font-bold '+(tab===id?'bg-indigo-600':'text-slate-400 hover:bg-slate-800')}>{label}</button>)}</nav></header><main className="max-w-6xl mx-auto p-4 md:p-6">
{tab==='schedule'&&<Card><h2 className="text-xl font-bold mb-4">{t.schedule}</h2><form onSubmit={addSchedule} className="grid md:grid-cols-4 gap-3 mb-5"><input name="time" placeholder={t.time} className="input"/><input name="title" placeholder={t.title} className="input"/><input name="location" placeholder={t.location} className="input"/><button className="btn">{t.add}</button></form>{schedule.map(x=><div key={x.id} className="row"><div><b>{x.title}</b><div className="text-xs text-slate-400">{x.time} · {x.location}</div></div><button onClick={()=>setSchedule(schedule.filter(y=>y.id!==x.id))} className="danger">{t.del}</button></div>)}</Card>}
{tab==='focus'&&<Card className="max-w-xl mx-auto text-center"><h2 className="text-xl font-bold">{t.focus}</h2><div className="text-7xl font-mono font-black text-indigo-400 my-8">{time}</div><div className="flex justify-center gap-2 mb-5"><input type="number" min="1" max="120" value={mins} onChange={e=>setMins(Math.max(1,+e.target.value||1))} className="input w-24 text-center"/><span className="self-center text-slate-400">{t.minutes}</span></div>{focus?<div className="flex justify-center gap-2"><button className="btn" onClick={()=>setFocus(false)}>{t.pause}</button><button className="danger" onClick={()=>{setFocus(false);setRemaining(mins*60)}}>{t.stop}</button></div>:<button className="btn px-8" onClick={()=>setFocus(true)}>{t.start}</button>}</Card>}
{tab==='tasks'&&<Card><h2 className="text-xl font-bold mb-4">{t.tasks}</h2><form onSubmit={addTask} className="grid md:grid-cols-4 gap-3 mb-5"><input name="task" placeholder={t.task} className="input"/><input name="date" type="date" className="input"/><select name="priority" className="input"><option value="high">{t.high}</option><option value="medium">{t.medium}</option><option value="low">{t.low}</option></select><button className="btn">{t.add}</button></form>{tasks.map(x=><div key={x.id} className="row"><label className="flex gap-3 items-center"><input type="checkbox" checked={x.completed} onChange={()=>setTasks(tasks.map(y=>y.id===x.id?{...y,completed:!y.completed}:y))}/><span className={x.completed?'line-through text-slate-500':''}>{x.title}<small className="block text-slate-500">{x.dueDate} · {x.priority}</small></span></label><button className="danger" onClick={()=>setTasks(tasks.filter(y=>y.id!==x.id))}>{t.del}</button></div>)}</Card>}
{tab==='matrix'&&<Card><h2 className="text-xl font-bold mb-5">{t.matrix}</h2><div className="grid md:grid-cols-2 gap-4">{[['high','rose',t.high],['medium','indigo',t.medium],['low','emerald',t.low]].map(([p,c,l])=><div key={p} className={'rounded-xl border border-'+c+'-500/30 bg-'+c+'-500/10 p-4'}><h3 className="font-bold mb-3">{l}</h3>{tasks.filter(x=>x.priority===p).map(x=><div key={x.id} className="bg-slate-900 rounded-lg p-3 mb-2">{x.title}</div>)}</div>)}</div></Card>}
{tab==='grades'&&<Card className="max-w-2xl mx-auto"><h2 className="text-xl font-bold mb-4">{t.grades}</h2><form onSubmit={addGrade} className="grid grid-cols-3 gap-3 mb-5"><input name="name" placeholder="Subject" className="input"/><input name="grade" type="number" min="0" max="100" placeholder="%" className="input"/><button className="btn">{t.add}</button></form>{grades.map(x=><div key={x.id} className="row"><b>{x.name}</b><span>{x.grade}% <button className="danger ml-3" onClick={()=>setGrades(grades.filter(y=>y.id!==x.id))}>{t.del}</button></span></div>)}<div className="mt-5 p-4 rounded-xl bg-slate-900 flex justify-between font-bold"><span>{t.avg}</span><span className="text-emerald-400">{avg}%</span></div></Card>}
{tab==='stats'&&<div className="grid md:grid-cols-3 gap-4">{[[t.total,stats.minutes,'min'],[t.sessions,stats.sessions,''],[t.streak,stats.streak,'days']].map(([a,b,c])=><Card key={a} className="text-center"><p className="text-slate-400 text-sm">{a}</p><b className="text-4xl text-indigo-400">{b}</b><small className="block text-slate-500">{c}</small></Card>)}</div>}
{tab==='whiteboard'&&<Board t={t}/>} {tab==='album'&&<Card><h2 className="text-xl font-bold mb-4">{t.album}</h2><input type="file" accept="image/*" multiple onChange={e=>[...e.target.files].forEach(file=>{const r=new FileReader();r.onload=()=>setPhotos(p=>[...p,{id:Date.now()+Math.random(),src:r.result,name:file.name}]);r.readAsDataURL(file)})} className="text-sm"/><div className="grid sm:grid-cols-2 md:grid-cols-3 gap-4 mt-5">{photos.map(p=><img key={p.id} src={p.src} alt={p.name} className="w-full h-48 object-cover rounded-xl border border-slate-700"/>)}</div></Card>}
{tab==='blocker'&&<Card><h2 className="text-xl font-bold mb-4">{t.blocker}</h2>{apps.map(a=><div key={a.id} className="row"><b>{a.name}</b><button onClick={()=>setApps(apps.map(x=>x.id===a.id?{...x,locked:!x.locked}:x))} className={a.locked?'danger':'btn'}>{a.locked?'BLOCKED':'ACTIVE'}</button></div>)}<p className="text-xs text-amber-400 mt-4">This web version controls the UI state only; real device-level blocking requires a native/device-management component.</p></Card>}
</main></div>}
function Board({t}){const ref=useRef(null),[tool,setTool]=useState('pen'),[down,setDown]=useState(false);useEffect(()=>{const c=ref.current,x=c.getContext('2d');x.fillStyle='#0f172a';x.fillRect(0,0,c.width,c.height)},[]);const pos=e=>{const r=ref.current.getBoundingClientRect(),p=e.touches?.[0]||e;return[(p.clientX-r.left)*ref.current.width/r.width,(p.clientY-r.top)*ref.current.height/r.height]};const move=e=>{if(!down)return;const x=ref.current.getContext('2d'),[a,b]=pos(e);x.strokeStyle=tool==='eraser'?'#0f172a':'#818cf8';x.lineWidth=tool==='eraser'?28:4;x.lineTo(a,b);x.stroke();x.beginPath();x.moveTo(a,b);e.preventDefault()};return <Card><div className="flex justify-between mb-4"><h2 className="text-xl font-bold">{t.whiteboard}</h2><div className="flex gap-2"><button className="btn" onClick={()=>setTool('pen')}>{t.pen}</button><button className="btn" onClick={()=>setTool('eraser')}>{t.eraser}</button><button className="danger" onClick={()=>{const x=ref.current.getContext('2d');x.fillStyle='#0f172a';x.fillRect(0,0,800,450)}}>{t.clear}</button></div></div><canvas ref={ref} width="800" height="450" className="w-full rounded-xl border border-slate-700 touch-none" onMouseDown={e=>{setDown(true);const x=ref.current.getContext('2d'),[a,b]=pos(e);x.beginPath();x.moveTo(a,b)}} onMouseUp={()=>setDown(false)} onMouseLeave={()=>setDown(false)} onMouseMove={move} onTouchStart={e=>{setDown(true);const x=ref.current.getContext('2d'),[a,b]=pos(e);x.beginPath();x.moveTo(a,b)}} onTouchEnd={()=>setDown(false)} onTouchMove={move}/></Card>}
export default App;
